### ISSUE TITLE
Need to republish -- issue in example code

### ISSUE THREAD

**Issue by EronHennessey** [awsdocs/aws-go-developer-guide#2]
This is in response to an [issue I received in the C++ dev guide](https://github.com/awsdocs/aws-cpp-developer-guide/issues/5), but was really for a Go SDK example.

I've [fixed it](https://github.com/awsdocs/aws-doc-sdk-examples/commit/48891a1c8e3587c9510a722d253691136e082f73)--we just need to get the guide rebuilt/republished to include the change.

Thanks!

**Comment by dghale** [comment]
I have just republished with the new example in place. Thanks!
