### ISSUE TITLE
Example on doc site missing lines

### ISSUE THREAD

**Issue by kwanlowe** [awsdocs/aws-go-developer-guide#21]
Hello. I arrived at this page from (https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ec2-example-manage-instances.html). On that page, the examples seem to be missing the relevant code sections. For example, the DescribeInstances example has an example that doesn't include the conn.DescribeInstances() call:

> 
> Call DescribeInstances to get detailed information for each instance.
> 
>     if err != nil {
>         fmt.Println("Error", err)
>     } else {
>         fmt.Println("Success", result)
>     }
> }

I tried to edit the page to pull in the extra relevant lines, but the included lines don't seem to match the code. For example, the code for the page shows:

> Call DescribeInstances to get detailed information for each instance.
> 
> .. literalinclude:: example_code/ec2/describing_instances.go
>    :lines: 35-41

But this doesn't match the lines on the example code:
> 43    // Call to get detailed information on each instance
> 44    result, err := ec2Svc.DescribeInstances(nil)
> 45    if err != nil {
> 46       fmt.Println("Error", err)
> 47    } else {
> 48        fmt.Println("Success", result)
> 49    }

**Comment by Doug-AWS** [comment]
Thanks, I'll fix the code example.

**Comment by Doug-AWS** [comment]
Fixed. It should be live by EOD.
